questions = {
    'What is the specific gravity of pure water?': '1',
    'What is almost always present in conjunction with atrial flutter?': 'AV block',
    'The Jervel and Lange-Nielsen syndrome is associated with QT prolongation and which other major feature?': 'Deafness',
    'What does neutrophilia refer to?\n\nA)Increased white blood cells\nB)Reduced white blood cells\nC)Increased neutrophils\nD)Reduced neutrophils': 'C',
    'Which of the following would NOT produce a restrictive pattern on spirometry?\n\nA)Asthma\nB)Scoliosis\nC)Large pleural effusion\nD)Motor neurone disease': 'A',
    'Which of the following supraventricular rhythms would be irregular?\n\nA)Focal atrial tachycardia\nB)Multifocal atrial tachycardia\nC)Typical atrial flutter\nD)AV nodal reentrant tachycardia': 'B',
    'What is the likely significance of circulating blasts on a blood film?\n\nA)Infection\nB)Acute leukaemia\nC)Megaloblastic anaemia\nD)Previous splenectomy': 'B',
    'Which of the following is NOT a glomerular cause of proteinuria?\n\nA)Lupus nephritis\nB)Amyloidosis\nC)Tubulointerstitial nephritis\nD)Diabetic nephropathy': 'C',
    "Which of the following is a cause of metabolic alkalosis?\n\nA)Diarrhoea\nB)Vomiting\nC)Cyanide toxicity\nD)Addison's disease": 'B',
    'What is the normal duration of the PR interval?\n\nA)<100 ms\nB)<120 ms\nC)100-120 ms\nD)120-200 ms': 'D',
    'Which of the following is NOT a cause of ketones in urine?\n\nA)Carbohydrate-free diet\nB)Diabetic ketoacidosis\nC)Starvation ketosis\nD)Low protein diet': 'D',
    'What would NOT be a cause of slow atrial fibrillation in a patient with previously known AF?\n\nA)Complete heart block\nB)Metoprolol\nC)Digoxin\nD)Thyrotoxicosis': 'D',
    'What is a common cause of reactive lymphocytes in the peripheral blood?\n\nA)Leukaemia\nB)Lymphoma\nC)Infectious mononucleosis\nD)Bacterial infection': 'C',
    'Which of the following is an irregular narrow complex tachyarrhythmia?\n\nA)Atrial fibrillation\nB)Typical atrial flutter\nC)AV reentrant tachycardia\nD)AV nodal reentrant tachycardia': 'A',
    'What is the direction of lead II on an ECG?\n\nA)0 degrees\n)B)30 degrees\nC)60 degrees\nD)90 degrees': 'C',
    'Which of the following is a cause of left shifted granulopoiesis?\n\nA)Bacterial infection\nB)Viral infection\nC)Allergy\nD)Megaloblastic anaemia': 'A',
    'Which of the following is NOT a cause of erythrocytosis?\n\nA)Smoking\nB)Polycythaemia vera\nC)EPO-producing tumour\nD)Alcohol': 'D',
    'Which of the following is a cause of an obstructive pattern on spirometry?\n\nA)Bronchiectasis\nB)Interstitial lung disease\nC)Chest wall deformity\nD)Pulmonary hypertension': 'A',
    'How are urine white cells estimated using a urine dipstick?\n\nA)Peroxidase reaction\nB)White cell membrane antibodies\nC)Leukocyte esterase\nD)Leukocyte microscopy': 'C',
    'True or false: the urethra is normally sterile.': 'False',
    'Which of the following is a cause of normal anion gap metabolic acidosis?\n\nA)Diarrhoea\nB)Lactic acidosis\nC)Diabetic ketoacidosis\nD)Ethylene glycol': 'A',
    'Which of the following is NOT a cause of diaphragmatic elevation?\n\nA)Lobectomy\nB)Pneumothorax\nC)Phrenic nerve palsy\nD)Ascites': 'B',
    'What is the normal QRS duration?\n\nA)80-120ms (2-3mm)\nB)120-160ms (3-4mm)\nC)120-200ms (3-5mm)\nD)160-200ms (4-5mm)': 'A',
    'What is the role of thyroid binding globulin (TBG)?\n\nA)Assists with thyroid hormone production\nB)Transports thyroid hormones\nC)Storage of thyroid hormones\nD)Assistance with thyroid hormone uptake': 'B',
    'Which of the following may manifest with ST depression?\n\nA)Hyperkalaemia\nB)Hypokalaemia\nC)Hypermagnesaemia\nD)Hypomagnesaemia': 'B',
    'Which of the following would be least likely to precipitate atrial fibrillation?\n\nA)Myocardial infarction\nB)Mitral stenosis\nC)Pulmonary embolism\nD)Pericardial effusion': 'D',
    'Which of the following typically produces a macrocytic, hyperchromic anaemia?\n\nA)Iron deficiency\nB)B12 deficiency\nC)EPO deficiency (chronic kidney disease)\nD)Thalassaemia': 'B',
    'Which of the following is NOT a cause of proteinuria?\n\nA)Minimal change disease\nB)Membranous glomerulonephropathy\nC)Focal segmental glomerulosclerosis\nD)Pyelonephritis': 'D',
    'What is the classic ECG finding in atrial fibrillation?\n\nA)Sawtooth waves\nB)Fibrillation waves\nC)Irregular P waves\nD)Flutter waves': 'B',
    'Basophilia is classically a feature of which type of disorder?\n\nA)Myeloproliferative neoplasms\nB)Myelodysplastic syndrome\nC)Acute leukaemia\nD)Bacterial infection': 'A',
    'Which of the following is NOT a cause of increased neutrophils?\n\nA)Bacterial infection\nB)Lymphoma\nC)Corticosteroids\nD)Chronic myeloid leukaemia': 'B', 
    'What condition is caused by the deposition of salts of uric acid?': 'gout',
    'Which disease is detected by using the Schilling test?': 'pernicious anemia',
    'Which of these is not a form of colour blindness?\n\nA)myopia\nB)deuteranopia\nC)protanopia\nD)tritanopia': 'A',
    'What is a more formal term for the disease called pinkeye?': 'conjunctivitis',
    'What fat-soluble substance present in green leafy vegetables was given its name because it is required for coagulation of the blood to take place?': 'Vitamin K',
    'What is eczema?\n\nA)a stomach disorder\nB)a type of seaweed\nC)an inflammatory skin condition\nD)loss of memory': 'C',
    'Chiropody is a name for a medical specialty whose history can be traced to 1500 BCE in Egypt. Which part of the human body does chiropody deal with?': 'feet',
    'When we suffer from belching, flatulence, aversion to eating, nausea, vomiting, diarrhea, constipation, and heartburn, we call it indigestion. What word would have been used in 18th-century Britain to describe the same symptoms?': 'dyspepsia',
    'In the 18th century, Englishman Stephen Hales inserted a tube into a blood vessel and allowed the blood to rise up the tube, thus measuring what aspect of circulation?': 'blood pressure',
    'Which fever is also called “three-day fever”?': 'pappataci fever',
    'If you become infested with worms, what kind of drug will you need?': 'anthelmintic',
    'What is the full name of the medical scanning technique called PET?': 'positron emission tomography',
    'Which brain disorder results in a progressive and irreversible decline in memory and various other cognitive functions?\n\nA)Hansen disease\nB)Huntington disease\nC)epilepsy\nD)Alzheimer disease': 'D',
    'Which of these diseases is called tabardillo in Mexico, where it killed the scientist who discovered how it was transmitted?\n\nA)sleeping sickness\nB)typhus\nC)cholera\nD)malaria': 'B', 
    'What does a dyslexic have trouble doing?\n\nA)maintaining eye-hand coordination\nB)remembering\nC)reading\nD)distinguishing right from left': 'C',
    'Which of these vitamins is water-soluble as opposed to fat-soluble?\n\nA)vitamin A\nB)vitamin D\nC)vitamin C\nD)vitamin E': 'C',
    'Which disease is caused by a deficiency of vitamin B12?\n\nA)pernicious anemia\nB)scurvy\nC)goitre\nD)night blindness': 'A',
    'Astigmatism affects which part of the human body?\n\nA)kidneys\nB)eyes\nC)elbows\nD)lymph nodes': 'B',
    'What is another name for breakbone fever?': 'dengue',
    'On what part of the body is a sphygmomanometer used?': 'arm',
    'Citrus fruits such as oranges, lemons, and limes protected the crews of sailing ships from scurvy, a disorder caused by a deficiency of which vitamin?': 'vitamin C',
    'What is the disease pertussis commonly known as?': 'whooping cough',
    'Which vitamin is also called niacin and prevents the skin lesions that are a symptom of pellagra?': 'vitamin B3',
    'Which of these is not a single vitamin but part of a group, or complex, of substances?\n\nA)vitamin D\nB)vitamin C\nC)vitamin B\nD)vitamin A': 'C',
    'Beriberi, meaning “extreme weakness,” is the name of a disorder caused by a lack of which vitamin?': 'vitamin B1',
    'What is the term for a localized collection of pus in a cavity formed from tissues that have been broken down by infectious bacteria?': 'abscess',
    'What is the generic term for inflammation of the mucous tissue of the nose?': 'rhinitis',
    'Whose principle—that bacteria must never gain entry to an operation wound—remains the basis of surgery to this day?': 'Joseph Lister',
    'Who developed the first safe and effective vaccine for polio?': 'Jonas Edward Salk',
    'What does thrombosis refer to?': 'blood clots',
    'Which disease is characterized by the thinning of bones, with a consequent tendency to sustain fractures?\n\nA)pernicious anemia\nB)fibrous dysplasia\nC)osteoporosis\nD)Paget disease': 'C',
    'Hypothermia can make a person appear dead. What is hypothermia?\n\nA)abnormally high body temperature\nB)an abnormal lack of sugar in the blood\nC)abnormally low body temperature\nD)a state of excessive emotion': 'C',
    'In 1851 the German physiologist Hermann von Helmholtz invented the ophthalmoscope. What is this instrument used for?\n\nA)counting eyelashes\nB)determining colour blindness\nC)examining the interior of the eye\nD)measuring the duration of a blink': 'C',
    'Hippocrates of Cos, who may or may not have lived during the 5th or 4th century BCE and probably did not write all the works commonly ascribed to him, is traditionally considered to be the father of which branch of science?': 'medicine',
    'Who was a pioneer in the diagnosis and treatment of brain tumours?\n\nA)Carol W. Greider\nB)Mae Jemison\nC)Barbara McClintock\nD)Harvey Williams Cushing': 'D',
    'What X-ray technique produces images of internal body structures as visual “slices” of the body?\n\nA)ultrasonography\nB)topography\nC)X-ray photography\nD)computerised tomography': 'D',
    'Which of these diseases is an example of zoonosis?\n\nA)rabies\nB)diphtheria\nC)malaria\nD)tetanus': 'A',
    'Who performed the first successful human heart transplant?\n\nA)Rosalind Franklin\nB)Christiaan Barnard\nC)Emily Blackwell\nD)Charles Richard Drew': 'B',
    'What is the disease tetanus also called?': 'lockjaw',
    'What condition is tachycardia, usually brought on by exercise or stress?\n\nA)sweating\nB)rapid breathing\nC)elevated body temperature\nD)rapid heartbeat': 'D',
    'If you see dark wavy lines on your skin and you are itchy at night, what sort of parasite might you have?\n\nA)worms\nB)mosquitoes\nC)fleas\nD)mites': 'D',
    'People get sick from eating Salmonella. What is it?\n\nA)an industrial chemical\nB)a fish\nC)bacteria\nD)a virus': 'C',
    'What condition is caused by the deposition of salts of uric acid?\n\nA)gout\nB)osteoporosis\nC)rheumatism\nD)arthritis': 'A',
    'Which of these is NOT a component of a neuron?\n\nA)hydrocephalus\nB)dendrites\nC)terminal buttons\nD)myelin sheath': 'A',
    'The part of the brain primarily responsible for production of speech is the ____.\n\nA)Broca area\nB)substantia nigra\nC)basal ganglia\nD)thalamus': 'A',
    'Prosopagnosia is also known as ____.\n\nA)face blindness\nB)sensory deprivation\nC)Alzeimer disease\nD)touch sensitivity': 'A',
    'A corpus callosotomy involves ____.\n\nA)draining excess fluid from the brain\nB)reattaching the spinal cord after it has been severed\nC)separating the two hemispheres of the brain\nD)removing the medulla': 'C',
    'Which of these is NOT a part of the brainstem?\n\nA)medulla oblongata\nB)midbrain\nC)pons\nD)cerebellum': 'D',
    'What is the function of the cerebral aqueduct?\n\nA)to control involuntary functions\nB)to connect the cerebellum to the spinal cord\nC)to release hormones into the blood\nD)to provide a pathway for cerebrospinal fluid inside the brain': 'D',
    'Which part of the brain controls the pituitary gland?\n\nA)hypothalamus\nB)homunculus\nC)hindbrain\nD)hippocampus': 'A',
    'Cells that nourish neurons are called ____.\n\nA)mitochodria\nB)ions\nC)fovea\nD)glia': 'D',
    'Which is the process involving the reabsorption of neurotransmitters within a synapse for later use?\n\nA)phylogeny\nB)cognition\nC)reuptake\nD)apoptosis': 'C',
    'Which is the primary function of the occipital lobe?\n\nA)regulation of the hunger drive\nB)reception of touch sensations\nC)reception of visual impulses\nD)regulation of the sleep cycle': 'C',
    'What causes the blood disease thalassemia?\n\nA)a genetic disorder\nB)nutrient deficiency\nC)parasitic fungi\nD)heavy metal poisoning': 'A',
    'What is the disease German measles also known as?': 'rubella',
    'What is the name of a malignant tumour of the bone, most often occurring in males under age 30?': 'osteosarcoma',
    'Which pioneering scientist received the Nobel Prize for Physiology or Medicine in 1983, when she was 81 years old, for her work on genes in the 1940s and the 1950s?\n\nA)Dorothy Mary Crowfoot Hodgkin\nB)Lise Meitner\nC)Rosalind Franklin\nD)Barbara McClintock': 'D',
    'What is Pickwickian syndrome associated with?': 'obesity',
    'Who discovered the major blood groups and developed the ABO system of blood typing, which made blood transfusion a routine medical practice?': 'Karl Landsteiner',
    'Who was the first person to describe the blood parasite responsible for malaria and to recognize it as the cause of that disease?': 'Alphonse Laveran',
    'Which of these viral diseases is also called variola?\n\nA)shingles\nB)chicken pox\nC)smallpox\nD)cowpox': 'C',
    'What 16th-century physician wrote that “a doctor must seek out old wives, gipsies, sorcerers, wandering tribes, old robbers, and such outlaws and take lessons from them. A doctor must be a traveller.… Knowledge is experience.”?\n\nA)Hippocates\nB)Socrates\nC)Mary Edwards Waler\nD)Paracelsus': 'D',
    'Who was the cofounder of modern neurology who greatly influenced a student named Sigmund Freud?\n\nA)Emily Blackwell\nB)Jean-Martin Charcot\nC)Nikolaas Tinbergen\nD)Eugen Bleuler': 'B',
    'Which hormone regulates the level of sugar in the blood and is produced in the pancreas?\n\nA)epinephrine\nB)insulin\nC)estrogen\nD)growth hormone': 'B',
    'Which of these is another name for growth hormone?\n\nA)insulin\nB)glucagon\nC)somatotropin\nD)epinephrine': 'C',
    'Which part of the human body does multiple sclerosis affect?\n\nA)reproductive system\nB)nervous system\nC)respiratory system\nD)digestive system': 'B',
    'What is the name of the disorder characterized by the patchy loss of melanin pigment from the skin?': 'vitiligo',
    "If you're stranded in the Arctic, why should you avoid eating polar bear liver?\n\nA)beriberi\nB)pernicious anemia\nC)hypervitaminosis A\nD)scurvy": 'C',
    'What determines the blood group in a person?': 'rhesus and AB antigens',
    'Who was the founder of modern psychosurgery?\n\nA)Antonio Egas Moniz\nB)William James\nC)Alfred Adler\nD)Florence Rena Sabin': 'A',
    'Which of these scientists helped in the development of azidothymidine (AZT), the first drug used in the treatment of AIDS?\n\nA)Barbara McClintock\nB)Gertrude B. Elion\nC)Maria Goeppert Mayer\nD)Anthony Fauci': 'B',
    'Which of these congenital disorders is characterized by an extra chromosome?\n\nA)Down syndrome\nB)Turner syndrome\nC)trisomy 13\nD)tetralogy of Fallot': 'A',
    'Which of these are produced in response to foreign substances called antigens?\n\nA)lymphocytes\nB)toxins\nC)antiglobulin\nD)antibodies': 'D',
    'What is the common name of acetylsalicylic acid, a compound that produces its well-known effects by inhibiting the production of prostaglandins?': 'aspirin',
    'What is vertigo?\n\nA)a state of dizziness\nB)fear of water\nC)fear of dogs\nD) fear of closed spaces': 'A',
    'Which of these conditions is also called “hardening of the arteries”?\n\nA)hypertophy\nB)heart attack\nC)arteriosclerosis\nD)hypertension': 'C',
    'What type of lung infection is tuberculosis?': 'bacterial',
    '"The capacity to think,decide and act on the bases of thought and decision freely & independently (without let or hindrance)" best describes: \n\nA)confidentiality\nB)autonomy\nC)reasonsed analysis\nD)virtue theory': 'B',
    'Which is the largest, strongest and longest bone of the body?': 'femur',
    'The blockage of arteries in the lungs is called?': 'pumonary embolism',
    'Which disease is caused due to the improper production or use of insulin?': 'diabetes',
    'The human body has more than ____ muscles.': '650',
    'A nephrologist is specialized in which organ of the body?': 'kidney',
    'Which blood type is considered as universal donor?': 'O negative',
    'The trachea belongs to which body system?': 'respiratory',
    'Which human organ is affected by Hepatitis A?': 'liver',
    'Aphakia is associated with which part of the body?': 'eye',
    'The disease in which eyelashes are loosed is called what?': 'madarosis',
    "Who is known as 'Father of Medicine'?": 'Hippocrates',
    'The inflammation of uterus is called what in medical science?': 'metritis',
    'The abnormal fear of blushing is known as _________ in medical language.': 'enrythrophobia',
    'Enteritis is the inflammation of which part of the body?': 'small intestine',
    'The branch of medical science in which we study the structure, arrangements and actions of the muscles is called _________.': 'myology',
    'Brachioplasty is associated with the surgery of _________.': 'arms',
    'The specialist of nose is known as what?': 'rhinologist',
    'A normal human being has how many taste buds?': '10000',
    'The movement of eyes during sleep is known as _________. (3 letters)': 'REM',
    'Which disease is caused due to the deficiency of vitamin C?': 'scurvy',
    'Which vein returns blood from brain to heart?': 'jugular veins',
    'The excess sugar as glycogen are stored in which organ of the body?': 'liver',
    'In medical language the itching of skin is known as _________.': 'pruritus',
    'Which tissue stores the fats in human body?': 'Adipose tissue',
    'The irritational fear of snow is called _________.': 'Chionophobia',
    'The inability of a person to speak is called what?': 'Aphonia',
    'The disorder of bones is known as _________.': 'osteoporosis',
    'Which form of cancer kills more human beings compared to other forms?': 'lung cancer',
    'What is cholangiocarcinoma?': 'bile duct cancer',
    'What are the hair-like projections on the outside of cells called?': 'cilia',
    'On a prescription medication, what does the abbreviation b.i.d. mean?': 'twice a day',
    'What do the initials "CME" stand for in medical terms?': 'Chief Medical Examiner',
    'The most common cause of sinusitis in adults is?': 'viral',
    'Where is the axillary temperature taken?': 'armpit',
    'In a medical context, something that is pertaining to the skin is known as what?': 'dermatologic',
    'What is the first priority in a trauma code?': 'airway',
    'Jaundice produces yellow pigmentation from which substance?': 'bilirubin',
    'What condition refers to a low oxygen level in the blood?': 'hypoxia',
    'A medical condition that has been caused by a physician or medical treatment is described as what?': 'Iatrogenic',
    'Pes planus refers to which condition?': 'flat feet',
    'What does "PO" stand for on a prescription?': 'By Mouth',
    'Who discovered the smallpox vaccine?': 'Edward Jenner',
    'A cancer or tumor of the liver is what condition?': 'Hepatoma',
    'What condition is characterized by an imbalance of salts or chemicals in the blood?': 'Electrolyte Imbalance',
    'What did psychologist Carl Jung develop?': 'The Archetype',
    'What is another name for "varicella"?': 'chickenpox',
    'Triskaidekaphobia is the term for the fear of which number?': '13',
    'What is the term used to describe the inflammation of the brain?': 'Encephalitis',
    'What sort of medical specialist is a cardiologist?': 'Heart Specialist',
    'What element can be used as an antidote for arsenic poisoning?': 'Selenium',
    'In emergency medicine, what does "STAT" mean?': 'immediately',
    'What digestive tract illness often is a manifestation of diabetes?': 'Gastroparesis',
    'What enzyme is responsible for breaking down starches?': 'amylase',
    'Which blood type is known as the "universal recipient?"': 'AB',
    'Which drug is a another name for diazepam?': 'Valium',
    'Cephalgia is a medical term for what malady?': 'headache',
    'What is pruritus?': 'itching',
    "What are unstable molecules that can attack the body's cells called?": 'Free Radicals',
    'Dermatitis is an inflammation of what part of the body?': 'skin',
    'In medicine, what does "GLOC" stand for?': 'Gravity Induced Lost Consciousness',
    'Typically, where in the heart is a pacemaker located?': 'right atrium',
    'The beginning phase or stage of a treatment is often referred to as what?': 'induction',
    'High blood pressure is also known as what?': 'Hypertension',
    'What does the "CAT" in CAT scan stand for?': 'Computerized Axial Tomography',
    'What medical term means "without symptoms"?': 'Asymptomatic',
    'The average heart beats how many times per minute?': '72',
    'Which medical term means vomiting?': 'emesis',
    'Something that is toward the end or away from the center of the body can also be called what?': 'distal',
    'Patients who present with traumatic injuries are evaluated using what score?': 'glasgow',
    'On which part of the body is an angioplasty performed?': 'blood vessel',
    'What do you call a doctor who specializes in treating the heart?': 'cardiologist',
    'According to Sigmund Freud, what is the instinctual and primitive part of the psyche?': 'Id',
    'What do the letters "EEG" stand for?': 'Electroencephalogram',
    'What condition is characterized by a stiff neck and fever?': 'meningitis',
    'If you are getting rid of a disease, what are you doing to it?': 'Eradicating',
    'What are the bones in the fingers called?': 'phalanges',
    'Who developed the vaccine for polio?': 'Jonas Salk',
    'If a doctor told you there was fluid entering your lungs, what term might he use to describe this?': 'aspiration',
    'The natural hallucinogen psilocybin is found in what?': 'mushrooms',
    'What German scientist is known as the Father of Radiology?': 'Wilhelm Roentgen',
    'What does "BMI" stand for?': 'Body Mass Index',
    'What disease does an endocrinologist generally study?': 'diabetes',
    'How many pairs of ribs are in a typical human body?': '12',
    'Matters related to what sense are referred to as olfactory?': 'smell',
    'The heart plays a pivotal role in which organ system?': 'circulatory',
    'When blood becomes more acid than normal, what it is the condition called?': 'Acidosis'
    }